spring:
  application:
    name: merchant

  datasource:
    url: jdbc:postgresql://localhost:5432/merchant_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
