spring:
  application:
    name: merchant

  datasource:
    url: jdbc:postgresql://localhost:5432/merchant_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: logs/merchant.log
  level:
    root: INFO
    com.test.merchant: DEBUG
#  pattern:
##    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
##    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"